nelmio_cors:
    defaults:
        origin_regex: false
        allow_credentials: false
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['*']
        max_age: 3600
    paths:
        '^/': null
# '%env(CORS_ALLOW_ORIGIN)%'
